version: "3.7"
services:

  postgres-applicant-service:
    image: postgres:14.6-alpine
    container_name: postgres-applicant-service
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=applicant_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./data/postgres_applicant_service:/var/lib/postgresql/data

  applicant-service:
    build: ./applicant-service
    restart: always
    image: applicant-service
    container_name: applicant-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-applicant-service:5432/applicant_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8081:8081"
    depends_on:
      - postgres-applicant-service

  cv-service:
    build: ./cv-service
    restart: always
    image: cv-service
    container_name: cv-service
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo-cv-service:27017/cv_service
    ports:
      - "8080:8080"
    depends_on:
      - mongo-cv-service

  mongo-cv-service:
    image: mongo:6.0.4-focal
    container_name: mongo-cv-service
    restart: always
    ports:
      - "27017:27017"
    expose:
      - "27017"
    volumes:
      - ./data/mongo_cv_service:/data/db

  angular:
    build: ./frontend-angular
    image: frontend-angular
    container_name: frontend-angular
    restart: always
    ports:
      - "4200:4200" # local execution via ng Serve
      - "80:80" # when running in nginx
    depends_on:
      - mongo-cv-service
