version: "3.7"
services:

  eureka-discovery-server:
    build: ./eureka-discovery-server
    restart: always
    image: eureka-discovery-server
    container_name: eureka-discovery-server
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8761:8761"

  api-gateway:
    build: ./api-gateway
    restart: always
    image: api-gateway
    container_name: api-gateway
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8080:8080"
    links:
      - eureka-discovery-server

  postgres-applicant-service:
    image: postgres:14.6-alpine
    container_name: postgres-applicant-service
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=applicant_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./data/postgres_applicant_service:/var/lib/postgresql/data

  mongo-cv-service:
    image: mongo:6.0.4-focal
    container_name: mongo-cv-service
    restart: always
    ports:
      - "27017:27017"
    expose:
      - "27017"
    volumes:
      - ./data/mongo_cv_service:/data/db

  applicant-service:
    build: ./applicant-service
    restart: always
    image: applicant-service
    container_name: applicant-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - postgres-applicant-service
      - api-gateway
      - eureka-discovery-server

  cv-service:
    build: ./cv-service
    restart: always
    image: cv-service
    container_name: cv-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - mongo-cv-service
      - api-gateway
      - eureka-discovery-server

  angular:
    build: ./frontend-angular
    image: frontend-angular
    container_name: frontend-angular
    restart: always
    ports:
      - "4200:4200" # local execution via ng Serve
      - "80:80" # when running in nginx
    depends_on:
      - cv-service
      - applicant-service
