version: "3.7"
services:
  # db:
  #   image: postgres:14.6-alpine
  #   container_name: db
  #   ports:
  #     - "5433:5432"
  #   environment:
  #     - POSTGRES_DB=demo
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #   volumes:
  #     - ./postgres_data:/var/lib/postgresql/data

  cv-service:
    build: ./cv-service
    restart: always
    image: cv-service
    container_name: cv-service
    environment:
      # - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/demo
      # - SPRING_DATASOURCE_USERNAME=postgres
      # - SPRING_DATASOURCE_PASSWORD=postgres
      # - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/cv_service
    ports:
      - "8080:8080"
    depends_on:
      - mongo

  mongo:
    container_name: mongo
    image: mongo:4.4.14-rc0-focal
    restart: always
    ports:
      - "27017:27017"
    expose:
      - "27017"
    volumes:
      - ./mongo-data:/data/db

  angular:
    build: ./frontend-angular
    image: frontend-angular
    container_name: frontend-angular
    restart: always
    ports:
      - "4200:4200" # local execution via ng Serve
      - "80:80" # when running in nginx
    depends_on:
      - mongo
