spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: cv-service
          uri: lb://cv-service
          predicates:
            - Path=/api/v1/cv/**
        - id: applicant-service
          uri: lb://applicant-service
          predicates:
            - Path=/api/v1/applicant/**
        - id: service-discovery
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/web
        - id: service-discovery-static
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

