spring:
  data:
    mongodb:
      uri: mongodb://mongo-cv-service:27017/cv_service
server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-discovery-server:8761/eureka
