spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/cv_service
      host: host.docker.internal
  application:
    name: cv-service
server:
  port: 0

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
